name: text_to_speech
description: A Flutter plugin provides TTS (Text-To-Speech) Service.
version: 0.2.2
homepage: https://github.com/ixsans/text_to_speech

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # federated plugin dependencies
  text_to_speech_macos: ^0.1.1
  text_to_speech_platform_interface: ^0.1.3
  text_to_speech_web: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ixsans.text_to_speech
        pluginClass: TextToSpeechPlugin
      ios:
        pluginClass: TextToSpeechPlugin
      web:
        default_package: text_to_speech_web
      macos:
        default_package: text_to_speech_macos

